import { GroovePreset, CoachLesson } from '../types/drums';

export const GROOVE_PRESETS: GroovePreset[] = [
  {
    id: 'basic-rock',
    name: 'Classic 4/4 Rock Beat',
    bpm: 108,
    description: 'The backbone of modern drumming! Kick on 1 & 3, Snare on 2 & 4, steady 8th-note Hi-Hats.',
    tracks: [
      { id: 'hihat-closed', steps: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false] },
      { id: 'snare',        steps: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false] },
      { id: 'kick',         steps: [true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false] },
      { id: 'crash',        steps: [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] },
    ]
  },
  {
    id: 'four-on-the-floor',
    name: 'Four-on-the-Floor Dance',
    bpm: 124,
    description: 'The infectious groove of electronic dance music with upbeat open hi-hats.',
    tracks: [
      { id: 'kick',         steps: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false] },
      { id: 'snare',        steps: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false] },
      { id: 'hihat-open',   steps: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false] },
      { id: 'hihat-closed', steps: [true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true] },
      { id: 'clap',         steps: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false] },
    ]
  },
  {
    id: 'hip-hop-boom-bap',
    name: '90s Hip Hop Boom-Bap',
    bpm: 92,
    description: 'Bouncy syncopated kick drum groove with a crisp backbeat snare and shaker.',
    tracks: [
      { id: 'kick',         steps: [true, false, false, false, false, false, false, false, false, false, true, false, false, true, false, false] },
      { id: 'snare',        steps: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false] },
      { id: 'hihat-closed', steps: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false] },
      { id: 'shaker',       steps: [false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true] },
    ]
  },
  {
    id: 'funk-pocket',
    name: 'Funky Pocket',
    bpm: 104,
    description: 'Funky ghost kicks and open hi-hat accents for deep pocket groove.',
    tracks: [
      { id: 'kick',         steps: [true, false, false, true, false, false, true, false, false, false, true, false, false, false, false, true] },
      { id: 'snare',        steps: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false] },
      { id: 'hihat-closed', steps: [true, true, true, false, true, true, true, false, true, true, true, false, true, true, false, true] },
      { id: 'hihat-open',   steps: [false, false, false, true, false, false, false, true, false, false, false, true, false, false, true, false] },
      { id: 'cowbell',      steps: [true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false] },
    ]
  },
  {
    id: 'rock-fill-break',
    name: 'Drum Fill Showcase',
    bpm: 112,
    description: 'Demonstrates a dynamic drum fill tumbling down high, mid, and floor toms into a crash!',
    tracks: [
      { id: 'kick',         steps: [true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false] },
      { id: 'snare',        steps: [false, false, false, false, true, false, false, false, true, true, false, false, false, false, false, false] },
      { id: 'tom-high',     steps: [false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false] },
      { id: 'tom-mid',      steps: [false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false] },
      { id: 'tom-low',      steps: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true] },
      { id: 'crash',        steps: [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] },
    ]
  }
];

export const COACH_LESSONS: CoachLesson[] = [
  {
    id: 'lesson-1',
    title: 'Lesson 1: The Heartbeat (Kick & Snare)',
    level: 'Beginner',
    bpm: 80,
    description: 'Learn the primary foundation of rhythm: Bass kick on Beat 1, Snare on Beat 2.',
    educationalTip: 'Count aloud: "ONE, TWO, THREE, FOUR". Hit the Kick pedal on 1 and 3, and hit the Snare drum on 2 and 4!',
    durationBeats: 16,
    notes: [
      { beat: 0, soundId: 'kick' },
      { beat: 1, soundId: 'snare' },
      { beat: 2, soundId: 'kick' },
      { beat: 3, soundId: 'snare' },
      { beat: 4, soundId: 'kick' },
      { beat: 5, soundId: 'snare' },
      { beat: 6, soundId: 'kick' },
      { beat: 7, soundId: 'snare' },
      { beat: 8, soundId: 'kick' },
      { beat: 9, soundId: 'snare' },
      { beat: 10, soundId: 'kick' },
      { beat: 11, soundId: 'snare' },
      { beat: 12, soundId: 'kick' },
      { beat: 13, soundId: 'snare' },
      { beat: 14, soundId: 'kick' },
      { beat: 15, soundId: 'snare' },
    ]
  },
  {
    id: 'lesson-2',
    title: 'Lesson 2: Adding the Steady Hi-Hat',
    level: 'Beginner',
    bpm: 85,
    description: 'Keep steady time with the closed Hi-Hat while alternating Kick and Snare.',
    educationalTip: 'Your right hand keeps the steady pulse on the Hi-Hat on every single beat while your foot and left hand alternate.',
    durationBeats: 16,
    notes: [
      { beat: 0, soundId: 'hihat-closed' },
      { beat: 0, soundId: 'kick' },
      { beat: 1, soundId: 'hihat-closed' },
      { beat: 1, soundId: 'snare' },
      { beat: 2, soundId: 'hihat-closed' },
      { beat: 2, soundId: 'kick' },
      { beat: 3, soundId: 'hihat-closed' },
      { beat: 3, soundId: 'snare' },
      { beat: 4, soundId: 'hihat-closed' },
      { beat: 4, soundId: 'kick' },
      { beat: 5, soundId: 'hihat-closed' },
      { beat: 5, soundId: 'snare' },
      { beat: 6, soundId: 'hihat-closed' },
      { beat: 6, soundId: 'kick' },
      { beat: 7, soundId: 'hihat-closed' },
      { beat: 7, soundId: 'snare' },
      { beat: 8, soundId: 'hihat-closed' },
      { beat: 8, soundId: 'kick' },
      { beat: 9, soundId: 'hihat-closed' },
      { beat: 9, soundId: 'snare' },
      { beat: 10, soundId: 'hihat-closed' },
      { beat: 10, soundId: 'kick' },
      { beat: 11, soundId: 'hihat-closed' },
      { beat: 11, soundId: 'snare' },
      { beat: 12, soundId: 'hihat-closed' },
      { beat: 12, soundId: 'kick' },
      { beat: 13, soundId: 'hihat-closed' },
      { beat: 13, soundId: 'snare' },
      { beat: 14, soundId: 'hihat-closed' },
      { beat: 14, soundId: 'kick' },
      { beat: 15, soundId: 'hihat-closed' },
      { beat: 15, soundId: 'snare' },
    ]
  },
  {
    id: 'lesson-3',
    title: 'Lesson 3: 8th Note Subdivisions (The Rock Groove)',
    level: 'Intermediate',
    bpm: 90,
    description: 'Level up to eighth notes: "1 and 2 and 3 and 4 and".',
    educationalTip: 'Notice the Hi-Hat now plays twice as fast on the "ands". That is called an 8th-note subdivision!',
    durationBeats: 16,
    notes: [
      // Measure 1
      { beat: 0, soundId: 'hihat-closed' },
      { beat: 0, soundId: 'kick' },
      { beat: 0.5, soundId: 'hihat-closed' },
      { beat: 1, soundId: 'hihat-closed' },
      { beat: 1, soundId: 'snare' },
      { beat: 1.5, soundId: 'hihat-closed' },
      { beat: 2, soundId: 'hihat-closed' },
      { beat: 2, soundId: 'kick' },
      { beat: 2.5, soundId: 'hihat-closed' },
      { beat: 3, soundId: 'hihat-closed' },
      { beat: 3, soundId: 'snare' },
      { beat: 3.5, soundId: 'hihat-closed' },

      // Measure 2
      { beat: 4, soundId: 'hihat-closed' },
      { beat: 4, soundId: 'kick' },
      { beat: 4.5, soundId: 'hihat-closed' },
      { beat: 5, soundId: 'hihat-closed' },
      { beat: 5, soundId: 'snare' },
      { beat: 5.5, soundId: 'hihat-closed' },
      { beat: 6, soundId: 'hihat-closed' },
      { beat: 6, soundId: 'kick' },
      { beat: 6.5, soundId: 'hihat-closed' },
      { beat: 7, soundId: 'hihat-closed' },
      { beat: 7, soundId: 'snare' },
      { beat: 7.5, soundId: 'hihat-closed' },

      // Measure 3
      { beat: 8, soundId: 'hihat-closed' },
      { beat: 8, soundId: 'kick' },
      { beat: 8.5, soundId: 'hihat-closed' },
      { beat: 9, soundId: 'hihat-closed' },
      { beat: 9, soundId: 'snare' },
      { beat: 9.5, soundId: 'hihat-closed' },
      { beat: 10, soundId: 'hihat-closed' },
      { beat: 10, soundId: 'kick' },
      { beat: 10.5, soundId: 'hihat-closed' },
      { beat: 11, soundId: 'hihat-closed' },
      { beat: 11, soundId: 'snare' },
      { beat: 11.5, soundId: 'hihat-closed' },

      // Measure 4
      { beat: 12, soundId: 'hihat-closed' },
      { beat: 12, soundId: 'kick' },
      { beat: 12.5, soundId: 'hihat-closed' },
      { beat: 13, soundId: 'hihat-closed' },
      { beat: 13, soundId: 'snare' },
      { beat: 13.5, soundId: 'hihat-closed' },
      { beat: 14, soundId: 'hihat-closed' },
      { beat: 14, soundId: 'kick' },
      { beat: 14.5, soundId: 'hihat-closed' },
      { beat: 15, soundId: 'hihat-closed' },
      { beat: 15, soundId: 'snare' },
      { beat: 15.5, soundId: 'hihat-closed' },
    ]
  },
  {
    id: 'lesson-4',
    title: 'Lesson 4: Rock Anthem (Double Kick & Crash)',
    level: 'Master',
    bpm: 96,
    description: 'Play a powerhouse anthem rock rhythm with syncopated double kicks.',
    educationalTip: 'Get ready for two quick kicks before beat 3! Lock into the groove and keep your limbs relaxed.',
    durationBeats: 16,
    notes: [
      // Measure 1
      { beat: 0, soundId: 'hihat-closed' },
      { beat: 0, soundId: 'kick' },
      { beat: 0.5, soundId: 'hihat-closed' },
      { beat: 1, soundId: 'hihat-closed' },
      { beat: 1, soundId: 'snare' },
      { beat: 1.5, soundId: 'hihat-closed' },
      { beat: 2, soundId: 'hihat-closed' },
      { beat: 2, soundId: 'kick' },
      { beat: 2.5, soundId: 'kick' },
      { beat: 3, soundId: 'hihat-closed' },
      { beat: 3, soundId: 'snare' },
      { beat: 3.5, soundId: 'hihat-closed' },

      // Measure 2
      { beat: 4, soundId: 'hihat-closed' },
      { beat: 4, soundId: 'kick' },
      { beat: 4.5, soundId: 'hihat-closed' },
      { beat: 5, soundId: 'hihat-closed' },
      { beat: 5, soundId: 'snare' },
      { beat: 5.5, soundId: 'hihat-closed' },
      { beat: 6, soundId: 'hihat-closed' },
      { beat: 6, soundId: 'kick' },
      { beat: 6.5, soundId: 'kick' },
      { beat: 7, soundId: 'hihat-closed' },
      { beat: 7, soundId: 'snare' },
      { beat: 7.5, soundId: 'hihat-closed' },

      // Measure 3
      { beat: 8, soundId: 'hihat-closed' },
      { beat: 8, soundId: 'kick' },
      { beat: 8.5, soundId: 'hihat-closed' },
      { beat: 9, soundId: 'hihat-closed' },
      { beat: 9, soundId: 'snare' },
      { beat: 9.5, soundId: 'hihat-closed' },
      { beat: 10, soundId: 'hihat-closed' },
      { beat: 10, soundId: 'kick' },
      { beat: 10.5, soundId: 'kick' },
      { beat: 11, soundId: 'hihat-closed' },
      { beat: 11, soundId: 'snare' },
      { beat: 11.5, soundId: 'hihat-closed' },

      // Measure 4
      { beat: 12, soundId: 'hihat-closed' },
      { beat: 12, soundId: 'kick' },
      { beat: 12.5, soundId: 'hihat-closed' },
      { beat: 13, soundId: 'hihat-closed' },
      { beat: 13, soundId: 'snare' },
      { beat: 13.5, soundId: 'hihat-closed' },
      { beat: 14, soundId: 'hihat-closed' },
      { beat: 14, soundId: 'kick' },
      { beat: 14.5, soundId: 'kick' },
      { beat: 15, soundId: 'hihat-closed' },
      { beat: 15, soundId: 'snare' },
      { beat: 15.5, soundId: 'hihat-closed' },
    ]
  }
];
